# Generated by Django 4.2.2 on 2023-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='topic',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
